### ISSUE TITLE
Replace the main context and cancel function by close function/channel

### ISSUE THREAD

**Issue by diligentis** [alicenet/alicenet#437]
As an alicenet developer, I would like to be able to close the task_handler, task_manager, task_executor and all the spawned tasks without using the context and cancel function.

Stop using the context functionality to close the task_handler, task_manager, task_executor and all the spawned tasks. Use a close function or channel instead to prevent the eventual memory leak.

Acceptance Criteria:

Usage of the main context is replaced by a close function or channel. It closes every element of the task execution chain. Unit tests added and passing.

**Comment by kosegor** [comment]
completed
