### ISSUE TITLE
Fork build does not contain version 

### ISSUE THREAD

**Issue by Cr0wn-Gh0ul** [alicenet/alicenet#459]
After forking the main repo and building the binary, if you try to run the binary it will panic.
```
panic: unexpected version format. expected vX.Y.Z[-optional]

goroutine 1 [running]:
github.com/alicenet/alicenet/cmd/node.validatorNode(0xc000124228?, {0xc000118420, 0x0, 0x2})
	/home/cr0wn/git/alicenet/cmd/node/node.go:198 +0x1a95
```
Resolves after adding upstream and running `git fetch --all --tags`.

**Comment by vtleonardo** [comment]
Documentation was updated to solve this issue: https://github.com/alicenet/alicenet/wiki/Dev%3A-Building
Users working on new forks should add the main repository as `remote`. This should avoid issues like this.
